trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - BAMTriviaProject2

pool:
  name: Default

variables:
  buildConfiguration: Debug
  solutionDir: BAMTriviaProject2

steps:
- script: dotnet restore
  workingDirectory: $(solutionDir)
  displayName: Restore

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  inputs:
    SonarCloud: sonarcloud
    organization: 1902-feb18-net
    projectKey: BAM1902trivia
    projectName: BAMTriviaProject2
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportsPaths="$(Build.ArtifactStagingDirectory)/test/*"
  displayName: Prepare analysis on SonarCloud

- script: dotnet build
    --configuration $(buildConfiguration)
    --no-restore
  workingDirectory: $(solutionDir)
  displayName: Build

- script: dotnet test **/*Test*.csproj
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/test
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput='$(Build.ArtifactStagingDirectory)/coverage/'
    /p:Exclude="[xunit*]*"
  workingDirectory: $(solutionDir)
  displayName: Test

- task: PublishTestResults@2
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '*'
    searchFolder: $(Build.ArtifactStagingDirectory)/test
  displayName: Publish test results

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: Run code analysis

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: Publish quality gate result

- script: dotnet publish **/BAMTriviaProject2.WebAPI.csproj
    --configuration $(buildConfiguration)
    --no-build
    --output $(Build.ArtifactStagingDirectory)/publish
  workingDirectory: $(solutionDir)
  displayName: Publish

- task: AzureRmWebAppDeployment@4
  displayName: Azure App Service deploy
  inputs:
    azureSubscription: 'Free Trial (74f13f66-859f-4fdc-8afa-2eabf78271b5)'
    WebAppName: BAM1902trivia
    packageForLinux: $(Build.ArtifactStagingDirectory)/publish
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
  condition: succeededOrFailed()
